// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: bookings.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
  id, 
  user_id, 
  showtime_id, 
  created_at, 
  updated_at
) VALUES (
  gen_random_uuid(), 
  $1, 
  $2,
  NOW(), 
  NOW()
)
RETURNING id, user_id, created_at, updated_at, showtime_id
`

type CreateBookingParams struct {
	UserID     uuid.UUID
	ShowtimeID uuid.UUID
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, createBooking, arg.UserID, arg.ShowtimeID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShowtimeID,
	)
	return i, err
}
