// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Booking struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	ShowtimeID uuid.UUID
}

type BookingSeat struct {
	ID        uuid.UUID
	BookingID uuid.UUID
	SeatCode  string
}

type Movie struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Title           string
	Description     string
	DurationMinutes int32
	PosterImageUrl  string
	TrailerVideoUrl string
	Rating          string
	Genre           string
	Director        string
	Casts           []string
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type Showtime struct {
	ID        uuid.UUID
	MovieID   uuid.UUID
	StartTime time.Time
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	UserRole       string
	HashedPassword string
}
