// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Booking struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	MovieID     uuid.UUID
	BookingTime time.Time
	SeatNumber  string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Movie struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Title           string
	Description     string
	DurationMinutes int32
	PosterImageUrl  string
	TrailerVideoUrl string
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
	UserRole  string
}
